version: '3.8'
services:
  database:
    image: postgres:10.3
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - DATABASE_URL='postgres://jhfwtzulslufrv:6d937d168784c7f6fa85150b5e9b909178b028ccf818eb10282a680629540f94@ec2-35-174-35-242.compute-1.amazonaws.com:5432/d4ufrn5v808l53'
      - ENVIRONMENT=PRODUCTION
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  server:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    env_file: ../.env
    depends_on:
      - database
    networks:
      - default
    ports:
      - '8080:8080'
volumes:
  postgres:
